'use strict';
const $=s=>document.querySelector(s);let catalog=[],photo='',rows=[],busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/\s+/g,'');
const localServer=$('meta[name=session-token]').content.length>30;
if(!localServer&&'serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
fetch(localServer?'/catalog':'drugs.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(j=>{catalog=Array.isArray(j)?j.map((d,i)=>({id:i+1,...d})):j.drugs;$('#status').textContent=localServer?`본원 약품 ${catalog.length}종 준비됨`:'본원 목록 검색 가능 · 사진 AI 판독은 내려받은 약 전용 PC 서버에서 사용하세요.'}).catch(()=>{$('#status').textContent='목록 로딩 실패. 페이지를 새로고침하세요.';$('#read').disabled=true;$('#manual').disabled=true});
async function setPhoto(file){if(!file)return;photo='';$('#read').disabled=true;$('#preview').hidden=true;$('#clearPhoto').hidden=true;try{if(file.size>20*1024*1024)throw Error('사진은 20MB 이하로 선택하세요.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,2200/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);photo=c.toDataURL('image/jpeg',.9);if(photo.length>8000000)throw Error('사진 용량이 큽니다. 약 부분만 잘라 다시 선택하세요.');$('#preview').src=photo;$('#preview').hidden=false;$('#clearPhoto').hidden=false;$('#status').textContent='사진 준비됨 · 아직 전송하지 않았습니다.';}finally{URL.revokeObjectURL(url)}}catch(e){photo='';$('#status').textContent=e.message||'사진을 읽지 못했습니다. JPG로 다시 선택하세요.'}finally{$('#read').disabled=!catalog.length;$('#consent').checked=false;invalidate()}}
function invalidate(){$('#results').hidden=true;$('#checked').checked=false}
$('#camera').onchange=e=>setPhoto(e.target.files[0]);$('#album').onchange=e=>setPhoto(e.target.files[0]);
$('#clearPhoto').onclick=()=>{photo='';$('#preview').removeAttribute('src');$('#preview').hidden=true;$('#clearPhoto').hidden=true;$('#camera').value='';$('#album').value='';$('#consent').checked=false;invalidate()};
$('#input').oninput=()=>{$('#consent').checked=false;invalidate()};
function renderRows(){const box=$('#rows');box.replaceChildren();rows.forEach((row,i)=>{const div=document.createElement('div');div.className='edit';div.innerHTML=`<label>약 이름<input data-key="name" value="${esc(row.name)}"></label><label>함량<input data-key="strength" value="${esc(row.strength)}"></label><label>성분·함량 원문<input data-key="ingredient" value="${esc(row.ingredient)}" placeholder="불확실하면 비워두세요"></label><p class="note">${esc(row.notes)}</p><button class="secondary">이 약 삭제</button>`;div.querySelectorAll('input').forEach(input=>input.oninput=()=>{row[input.dataset.key]=input.value;row.alternatives=[];row.notes='수정됨 · 기존 AI 대체 후보 제외';div.querySelector('.note').textContent=row.notes;invalidate()});div.querySelector('button').onclick=()=>{rows.splice(i,1);renderRows();invalidate()};box.append(div)});$('#verify').hidden=false;invalidate()}
$('#add').onclick=()=>{rows.push({name:'',strength:'',ingredient:'',notes:'직접 입력',alternatives:[]});renderRows()};
$('#read').onclick=async()=>{if(!localServer){$('#status').textContent='사진 AI 판독은 약 전용 PC 서버 주소에서 사용하세요. GitHub Pages에서는 본원 목록 검색만 가능합니다.';return}if(busy)return;if(!photo&&!$('#input').value.trim()){$('#status').textContent='사진 또는 약 이름을 입력하세요.';return}if(!$('#consent').checked){$('#status').textContent='자료 전송 확인란을 체크하세요.';return}busy=true;$('#read').disabled=true;$('#verify').hidden=true;invalidate();$('#status').textContent='판독 중입니다. 최대 약 3분 걸릴 수 있습니다.';const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),180000);try{const r=await fetch('/generate',{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':$('meta[name=session-token]').content},body:JSON.stringify({history:$('#input').value,photos:photo?[photo]:[],treatments:[]}),signal:ctl.signal});const j=await r.json();if(!r.ok)throw Error(j.error||'판독 오류');rows=j.drugs;renderRows();$('#status').textContent=rows.length?`${rows.length}개 약 판독 · 원문과 대조해주세요.`:'읽을 수 있는 약이 없습니다. 다시 촬영하거나 직접 입력하세요.';$('#verify').scrollIntoView({behavior:'smooth'})}catch(e){$('#status').textContent=e.name==='AbortError'?'응답 시간이 초과되었습니다. 사진을 줄여 다시 시도하세요.':e.message}finally{clearTimeout(timer);busy=false;$('#read').disabled=false}};
function card(d,reason=''){return `<div class="candidate"><b>${esc(d.name)}</b><div>${esc(d.ingredient||'성분 자료 없음')}</div><div class="meta">함량: ${esc(d.strength||'확인 필요')} · ${esc(d.sheet)} · 코드 ${esc(d.code)}<br>${esc(d.efficacy)}</div>${reason?`<p class="note">AI 제안 사유: ${esc(reason)}</p>`:''}</div>`}
function matches(row){const key=norm(row.ingredient);return key?catalog.filter(d=>d.ingredient&&norm(d.ingredient)===key):[]}
$('#match').onclick=()=>{if(!$('#checked').checked){alert('약 이름·성분·함량을 대조한 뒤 확인란을 체크하세요.');return}$('#resultList').innerHTML=rows.filter(r=>r.name.trim()).map(row=>{const same=matches(row),ids=new Set(same.map(d=>d.id));const alt=row.alternatives.filter(a=>!ids.has(a.id)).map(a=>({d:catalog.find(d=>d.id===a.id),reason:a.reason})).filter(a=>a.d);return `<article><h3>${esc(row.name)} ${esc(row.strength)}</h3><h4>① 동일 성분 후보</h4><p class="meta">확인한 성분·함량 문자열과 본원 자료가 일치한 항목입니다. 제형·경로·방출형은 별도 대조하세요.</p>${same.length?same.map(d=>card(d)).join(''):'<p>확인된 일치 항목 없음 · 미등록 또는 표기 차이일 수 있습니다.</p>'}<h4>② 대체 검토 후보</h4>${alt.length?alt.map(a=>card(a.d,a.reason)).join(''):'<p>제시할 대체 후보가 없습니다.</p>'}<p class="note">${esc(row.notes)}</p></article>`}).join('');$('#results').hidden=false;$('#results').scrollIntoView({behavior:'smooth'})};
$('#manual').onclick=()=>{$('#search').hidden=false;$('#query').value=$('#input').value.split('\n')[0];search();$('#search').scrollIntoView({behavior:'smooth'})};
function search(){const q=norm($('#query').value);const found=q?catalog.filter(d=>norm(d.name).includes(q)||norm(d.ingredient).includes(q)):[];$('#searchResults').innerHTML=found.length?found.map(d=>card(d)).join(''):'<p>검색어를 입력하거나 성분명으로 다시 찾아보세요.</p>'}
$('#query').oninput=search;$('#reset').onclick=()=>location.reload();
