const $=s=>document.querySelector(s);let file=null,DRUGS=[];
fetch('hospital-drugs-source.html').then(r=>r.text()).then(t=>{const m=t.match(/const DRUGS = (\\[[\\s\\S]*?\\]);\\s*const normalize/);if(!m)throw Error('본원 약품 목록을 읽지 못했습니다.');DRUGS=JSON.parse(m[1]);$('#match').disabled=false;}).catch(()=>alert('본원 약품 목록을 읽지 못했습니다.'));
const normalize=s=>(s||'').toLowerCase().replaceAll('㎎','mg').replaceAll('㎖','ml').replace(/염산염|수화물|나트륨|마그네슘|말레산염|베실산염/g,'').replace(/[^가-힣a-z0-9]/g,'');
const strength=s=>((s||'').toLowerCase().replaceAll('㎎','mg').replaceAll('㎖','ml').match(/\d+(?:\.\d+)?\s*(?:mg|g|mcg|ml|%|iu|단위)/g)||[]).join('/');
function setPhoto(f){if(!f)return;file=f;$('#preview').src=URL.createObjectURL(f);$('#previewWrap').hidden=false}
$('#photo').onchange=e=>setPhoto(e.target.files[0]);$('#gallery').onclick=()=>$('#photo').click();
$('#remove').onclick=()=>location.reload();$('#restart').onclick=()=>location.reload();
function editRow(d={name:'',strength:''}){const el=document.createElement('div');el.className='drugEdit';el.innerHTML=`<input class="drugName" aria-label="약 이름" placeholder="약 이름 또는 성분" value="${escapeHtml(d.name||'')}"><input class="drugStrength" aria-label="함량" placeholder="함량" value="${escapeHtml(d.strength||'')}"><button class="delete" aria-label="삭제">×</button>`;el.querySelector('.delete').onclick=()=>el.remove();return el}
function renderRecognized(items){const box=$('#recognized');box.innerHTML='';(items.length?items:[{}]).forEach(x=>box.append(editRow(x)));const add=document.createElement('button');add.className='add';add.textContent='+ 약 직접 추가';add.onclick=()=>box.insertBefore(editRow(),add);box.append(add);$('#verify').hidden=false;$('#verify').scrollIntoView({behavior:'smooth'})}
$('#analyze').onclick=async()=>{const url=localStorage.getItem('drugVisionEndpoint');if(!url){alert('사진 판독 서버가 아직 연결되지 않았습니다. 우선 약 이름을 직접 확인해 주세요.');renderRecognized([]);return}const fd=new FormData();fd.append('image',file);$('#analyze').textContent='읽는 중…';$('#analyze').disabled=true;try{const r=await fetch(url,{method:'POST',body:fd});if(!r.ok)throw Error('서버 오류');const j=await r.json();renderRecognized(j.drugs||[])}catch(e){alert('사진 판독에 실패했습니다. 약 이름을 직접 입력해 주세요.');renderRecognized([])}finally{$('#analyze').textContent='약 목록 읽기';$('#analyze').disabled=false}};
function score(d,q){const nq=normalize(q.name),ni=normalize(d.ingredient),nn=normalize(d.name),qs=normalize(q.strength),ds=normalize(d.strength);let n=0;if(nq&&ni.includes(nq))n=100;else if(nq&&nn.includes(nq))n=95;else if(nq.length>=3&&(nq.includes(ni)||nn.includes(nq.slice(0,3))))n=65;if(qs&&ds&&qs===ds)n+=20;return n}
function findMatches(q){const ranked=DRUGS.map(d=>({...d,_score:score(d,q)})).filter(d=>d._score>=65).sort((a,b)=>b._score-a._score);const exact=ranked.filter(d=>d._score>=95);if(exact.length)return{same:exact.slice(0,5),alt:[]};const words=(q.efficacy||'').split(/[,\s/]+/).filter(x=>x.length>1);const qCandidate=ranked[0];const group=(qCandidate?.efficacy||q.efficacy||'').split(/[,()]/).map(x=>x.trim()).filter(x=>x.length>2);const keys=[...new Set([...words,...group])];const alt=keys.length?DRUGS.filter(d=>keys.some(k=>(d.efficacy||'').includes(k))).slice(0,6):[];return{same:[],alt}}
function candidate(d){return `<div class="candidate"><b>${escapeHtml(d.name)}</b><div class="meta">${escapeHtml(d.ingredient||'성분 자료 확인 필요')} · ${escapeHtml(d.strength||'함량 자료 확인 필요')}</div></div>`}
$('#match').onclick=()=>{const items=[...document.querySelectorAll('.drugEdit')].map(x=>({name:x.querySelector('.drugName').value.trim(),strength:x.querySelector('.drugStrength').value.trim()})).filter(x=>x.name);if(!items.length){alert('약 이름을 한 개 이상 입력해 주세요.');return}$('#resultList').innerHTML=items.map(q=>{const m=findMatches(q);return `<article class="drugResult"><div class="source">${escapeHtml(q.name)} <span class="meta">${escapeHtml(q.strength)}</span></div>${m.same.length?`<div class="bucket same"><div class="bucketTitle">① 동일성분 본원약</div>${m.same.map(candidate).join('')}</div>`:`<div class="bucket none"><div class="bucketTitle">① 동일성분 본원약</div><div class="meta">확인된 동일성분 약이 없습니다.</div></div>`}${!m.same.length?`<div class="bucket alt"><div class="bucketTitle">② 대체 가능 목록</div>${m.alt.length?m.alt.map(candidate).join(''):'<div class="meta">승인된 대체 규칙이 없어 후보를 표시하지 않습니다.</div>'}<div class="warning">적응증·금기·상호작용·제형 확인 후 의료진이 결정</div></div>`:''}</article>`}).join('');$('#results').hidden=false;$('#results').scrollIntoView({behavior:'smooth'})};
function escapeHtml(s){return(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#openSettings').onclick=()=>{$('#endpoint').value=localStorage.getItem('drugVisionEndpoint')||'';$('#settings').showModal()};$('#saveSettings').onclick=()=>localStorage.setItem('drugVisionEndpoint',$('#endpoint').value.trim());if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
